# Site settings
title: El Blog de armonge
email: me@armonge.info
description: > # this means to ignore newlines until "baseurl:"
  Just some random thoughts on programming and life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://armonge.info" # the base hostname & protocol for your site
enforce_ssl: armonge.info
twitter_username: armonge
github_username:  armonge

# Build settings
markdown: kramdown

kramdown:
  input: GFM

gems:
  - jekyll-redirect-from
